def larger_CNN(num_classes, image_shape):
  model = Sequential()
  model.add(Reshape((1, image_shape[0], image_shape[1]), input_shape = image_shape))
  model.add(Convolution2D(50, 3, 3, border_mode=’same’, activation=’relu’))
  model.add(MaxPooling2D(pool_size=(2, 2),dim_ordering="th"))
  model.add(Convolution2D(40, 3, 3, border_mode=’same’, activation=’relu’)
  )model.add(MaxPooling2D(pool_size=(2, 2),dim_ordering="th"))
  model.add(Convolution2D(30, 3, 3, border_mode=’same’, activation=’relu’))
  model.add(MaxPooling2D(pool_size=(2, 2),dim_ordering="th"))
  model.add(Dropout(0.2))model.add(Flatten())
  model.add(Dense(400, activation=’relu’))
  model.add(Dropout(0.2))
  model.add(Dense(250, activation=’relu’))
  model.add(Dense(num_classes, activation=’softmax’))
  return model
